version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "coster"
    schedule:
      interval: "weekly"
      day: "saturday"
    groups:
      xunit:
        patterns:
          - xunit
          - xunit.analyzers
          - xunit.runner.visualstudio
