version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "coster"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: "FluentAssertions"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.Hosting"
        update-types: ["version-update:semver-major"]
    groups:
      xunit:
        patterns:
          - xunit
          - xunit.analyzers
          - xunit.runner.visualstudio
