pool:
  vmImage: 'Ubuntu-20.04'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - coster/*
    - coster.yml

pr:
  branches:
    include:
    - main
  paths:
    include:
    - coster/*
    - coster.yml

steps:

- task: DotNetCoreInstaller@2
  displayName: Install .NET Core SDK 6.0.100
  inputs:
    packageType: 'sdk'
    version: '6.0.100'

- bash: |
    dotnet test --logger trx --results-directory $(Common.TestResultsDirectory) --output $(Build.StagingDirectory)
  workingDirectory: coster
  displayName: dotnet test

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '*.trx'
    testResultsFormat: 'VSTest'
    searchFolder: $(Common.TestResultsDirectory)
    publishRunAttachments: true
  condition: succeededOrFailed()
  displayName: Publish tests results
