pool:
  vmImage: 'Ubuntu-20.04'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - parser/*
    - parser.yml

schedules:
- cron: "20 0 * * *"
  displayName: Daily
  branches:
    include:
    - main
  always: true

steps:

- bash: |
    yarn set version berry
  displayName: 'Use Yarn Modern'

- bash: |
    yarn install
  displayName: 'yarn install'
  workingDirectory: parser

- bash: |
    yarn test-ci
  env:
    JEST_JUNIT_OUTPUT_DIR: '$(Common.TestResultsDirectory)'
    JEST_JUNIT_OUTPUT_NAME: unit.xml
  workingDirectory: parser
  displayName: yarn test

- bash: |
    sudo apt-get update
    sudo apt-get install -y libgbm1
  displayName: Install libgbm1 (required by Puppeteer 3)

- bash: |
    yarn e2e-all-ci
  env:
    JEST_JUNIT_OUTPUT_DIR: '$(Common.TestResultsDirectory)'
    JEST_JUNIT_OUTPUT_NAME: e2e-all.xml
  workingDirectory: parser
  displayName: yarn e2e

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '*.xml'
    testResultsFormat: 'JUnit'
    searchFolder: $(Common.TestResultsDirectory)
  condition: succeededOrFailed()
  displayName: Publish tests results
