pool:
  vmImage: 'Ubuntu-18.04'

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - parser/*
    - parser.yml

schedules:
- cron: "20 0 * * *"
  displayName: Daily
  branches:
    include:
    - master
  always: true

steps:

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
  displayName: Install Yarn 1.21.1
  inputs:
    versionSpec: 1.21.1

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-task.Yarn@3
  displayName: yarn install
  inputs:
    arguments: install
    projectDirectory: parser

- bash: |
    yarn test-ci
  env:
    MOCHA_FILE: '$(Common.TestResultsDirectory)/test-results.xml'
  workingDirectory: parser
  displayName: yarn test

- bash: |
    yarn e2e-ci
  env:
    MOCHA_FILE: '$(Common.TestResultsDirectory)/e2e-results.xml'
  workingDirectory: parser
  displayName: yarn e2e

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '*.xml'
    testResultsFormat: 'JUnit'
    searchFolder: $(Common.TestResultsDirectory)
    publishRunAttachments: true
  condition: succeededOrFailed()
  displayName: Publish tests results
