name: Coster build
on:
  push:
    branches:
      - main
    paths:
      - 'coster/**'
      - .github/workflows/coster.yml
  pull_request:
    branches:
      - main
    paths:
      - 'coster/**'
      - .github/workflows/coster.yml
env:
  BUILD_CONFIGURATION: Release
jobs:
  build:
    name: Coster Build
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: coster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Dotnet format
        run: dotnet format --verify-no-changes
      - name: Build
        run: dotnet build --configuration $BUILD_CONFIGURATION --no-restore
      - name: Test
        run: dotnet test --configuration $BUILD_CONFIGURATION --no-build --logger "trx;LogFileName=${{ github.workspace }}/coster/artifacts/test-results/test-results.trx"
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: 'coster/artifacts/test-results/*.trx'
          if-no-files-found: error
