name: Parser tests
on:
  push:
    branches:
      - main
    paths:
      - 'parser/**'
      - .github/workflows/parser.yml
  pull_request:
    branches:
      - main
    paths:
      - 'parser/**'
      - .github/workflows/parser.yml
jobs:
  tests:
    name: Parser tests
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: parser
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: yarn install
        run: yarn install
      - name: Set test results path environment variable
        run: echo "TEST_RESULTS_PATH=${{ runner.temp }}/test-results" >> $GITHUB_ENV
      - name: yarn test
        run: yarn test-ci
        env:
          JEST_HTML_REPORTER_OUTPUT_PATH: ${{ env.TEST_RESULTS_PATH }}/unit.html
      - name: yarn e2e
        run: yarn e2e-all-ci
        env:
          JEST_HTML_REPORTER_OUTPUT_PATH: ${{ env.TEST_RESULTS_PATH }}/e2e-all.html
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: ${{ env.TEST_RESULTS_PATH }}
          if-no-files-found: error
      - name: Upload unit tests coverage
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: ${{ github.workspace }}/parser/coverage/lcov-report
          if-no-files-found: error
