name: Coster build
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'coster/**'
      - .github/workflows/coster.yml

jobs:
  build:
    name: Coster Build
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Handling skipped but required check, see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks"
